Timx/zhy 13 实现user模块的api路由
zolran-studio/zhihuyou.server pull request #15
Opened 2021-05-16 16:42 UTC by Whx-Tim

新增UsersController:实现后台的CRUD，客户端的修改密码与修改firstname & lastname；新增PrismaErrorCode文件：对应known exception code；新增constants：进行系统固定配置的调用项；新增Roles装饰器：对用户的角色权限进行控制；新增Serializer装饰器：针对返回的数据统一进行序列化；

2021-05-16 17:12 UTC, CaliCastle requested changes
总的来说挺棒的 小地方稍微改动一下就没问题
👍🏼  🎊

2021-05-16 17:12 UTC, CaliCastle commented on src/config/index.ts
> +    expiresIn: '120m',
变成了2小时有具体原因么

2021-05-16 17:12 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
> +  async search(@Query() data: SearchUserDto) {
wow 666 超出了大纲也完成了

2021-05-16 17:12 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
> +  }
这个应该不用限制ADMIN吧

2021-05-16 17:12 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
> +  @ApiOkResponse({ type: User })
nit: 除了Get以外都不是 "OK" 而是 "Created"

2021-05-16 17:12 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
>  export class UsersController {
nit: 没有添加强制 AuthGuard

2021-05-16 17:12 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
> +  @Put('update/me')
```suggestion
  @Put('my')
```

2021-05-16 17:12 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
> +  @Put('me/password')
```suggestion
  @Put('my/password')
```

2021-05-16 17:12 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
>  export class UsersController {
虽然 @Roles decorator里面有用到 不过还是添加宏观比较保险

2021-05-16 17:12 UTC, CaliCastle commented on src/core/interceptors/serializer.interceptor.ts
> +    this.app = {}
好像app不再需要了？

2021-05-16 17:12 UTC, CaliCastle commented on src/enums/PrismaErrorCode.ts
> +  NotFound = 'P2025',
Nice

2021-05-16 17:12 UTC, CaliCastle commented on src/guards/roles.guard.ts
> +      !this.isAdmin(user!)
三连否定需要一点点时间才能读懂 😂

2021-05-16 17:12 UTC, CaliCastle commented on src/guards/roles.guard.ts
> +      !this.isAdmin(user!)
看看有没有更好的描述方法

2021-05-16 17:12 UTC, CaliCastle commented on src/services/users/admin.service.ts
> +const defaultPassword = 'zolran666'
`666`

2021-05-16 17:12 UTC, CaliCastle commented on src/services/users/admin.service.ts
> +    const hashPassword = await this.hash.make(password)
```suggestion
    const hashedPassword = await this.hash.make(password)
```

2021-05-16 17:12 UTC, CaliCastle commented on src/services/users/admin.service.ts
> +  async forceUpdate(data: ForceUpdateUserDto, id: string): Promise<User> {
设计来说有一点点反向思维，一般不是id在前么

2021-05-16 17:12 UTC, CaliCastle commented on src/services/users/admin.service.ts
> +   * Create a user.
```suggestion
   * Creates a user.
```

2021-05-16 17:12 UTC, CaliCastle commented on src/services/users/admin.service.ts
> +   * Gets all users orderBy desc createdAt
```suggestion
   * Gets all users (latest first)
```

2021-05-16 17:12 UTC, CaliCastle commented on src/services/users/admin.service.ts
> +        [item[0], Object.fromEntries([['contains', item[1]]])],
可以再多点括号？ 😂

2021-05-16 17:12 UTC, CaliCastle commented on src/types/user/user.ts
> +  email!: string
```suggestion
  @ApiProperty()
  @IsNotEmpty()
  @IsEmail()
  email!: string
```

2021-05-16 17:12 UTC, CaliCastle commented on src/types/user/user.ts
> +export class CreateUserDto {
其实可以借用一下RegisterDto

2021-05-16 17:12 UTC, CaliCastle commented on src/types/user/user.ts
> +export class CreateUserDto {
extends

2021-05-16 17:12 UTC, CaliCastle commented on src/types/user/user.ts
> +  password!: string
尽量添加一下 @MinLength(6)  吧

2021-05-16 17:12 UTC, CaliCastle commented on src/types/user/user.ts
> +  oldPassword!: string
```suggestion
  currentPassword!: string
```

2021-05-16 17:12 UTC, CaliCastle commented on src/types/user/user.ts
> +import { ApiProperty } from '@nestjs/swagger'
这个文件重复率有点高了 🤔

2021-05-16 17:12 UTC, CaliCastle commented on test/helpers.ts
> +  }
nice

2021-05-16 17:12 UTC, CaliCastle commented on test/helpers.ts
> +  return request(app.getHttpServer())
哈哈哈 够懒的

2021-05-16 17:14 UTC, Whx-Tim commented on src/config/index.ts
> +    expiresIn: '120m',
主要是登录的时长~ 如果没有标记remember me 的话，一般的session也是2h这样~ 而且这样也方便本地api测试~

2021-05-16 17:16 UTC, Whx-Tim commented on src/controllers/users/users.controller.ts
> +  }
因为用户只能看到自己的user才是，如果需要查看别人的user信息的话，应该需要封装一下，而不是直接看到所有的信息。比如createdAt这些就不需要暴露给其他用户查看其他用户的时候看到，然后用户查看其他用户的话，我是设想着在profile那里实现，在profile当中携带一下用户的email firstname lastname这些。

2021-05-16 17:17 UTC, Whx-Tim commented on src/controllers/users/users.controller.ts
> +  @ApiOkResponse({ type: User })
update也是created吗？

2021-05-16 17:18 UTC, Whx-Tim commented on src/controllers/users/users.controller.ts
>  export class UsersController {
就是因为这里面的权限分开了，也是，controller的AuthGuard也需要显性一些~

2021-05-16 17:19 UTC, Whx-Tim commented on src/controllers/users/users.controller.ts
> +  @Put('update/me')
这个因为跟update操作时使用的@param(':id')匹配了，而且用的cuid，也是string类型的，不然就要过滤掉专门的string了

2021-05-16 17:23 UTC, Whx-Tim commented on src/core/interceptors/serializer.interceptor.ts
> +    this.app = {}
卧槽！这个之前测试的东西没删掉，这次commit的东西比较多，跑起来正常就没检查到位。这个app是想作为一个model寄存器的，想要测试一下能不能不用每次都实例化model，测试完之后不可以，不实例化的话，model就会使用同一个地址，这样会影响所有的serializer。

2021-05-16 17:33 UTC, Whx-Tim commented on src/guards/roles.guard.ts
> +      !this.isAdmin(user!)
ok，已调整。

2021-05-16 17:34 UTC, Whx-Tim commented on src/services/users/admin.service.ts
> +    const hashPassword = await this.hash.make(password)
😯

2021-05-16 17:36 UTC, Whx-Tim commented on src/services/users/admin.service.ts
> +        [item[0], Object.fromEntries([['contains', item[1]]])],
233~ 你想要的话，还可以~

2021-05-16 17:37 UTC, Whx-Tim commented on src/types/user/user.ts
> +  email!: string
😯  ！！！

2021-05-16 17:43 UTC, Whx-Tim commented on src/types/user/user.ts
> +export class CreateUserDto {
这个是因为Password需要optional，管理员新建的时候，可能不需要密码，直接使用默认密码来创建用户。

2021-05-16 17:43 UTC, Whx-Tim commented on src/types/user/user.ts
> +  password!: string
ok

2021-05-16 17:46 UTC, Whx-Tim commented on src/types/user/user.ts
> +import { ApiProperty } from '@nestjs/swagger'
确实，变成classDecorator ?

2021-05-16 23:24 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
> +  }
嗯OK

2021-05-16 23:25 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
> +  @ApiOkResponse({ type: User })
只有Get请求成功以后会返回OK（200） 如果是Post Put Delete返回成功的话都是Created（201）

2021-05-16 23:25 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
> +  @Put('update/me')
那就把这个优先级调高一点吧

2021-05-17 02:30 UTC, CaliCastle approved these changes
LGTM

2021-05-17 02:30 UTC, CaliCastle commented on src/guards/roles.guard.ts
> +  private checkHaveRole(roles: [], user: User): boolean {
```suggestion
  private checkHaveRole(roles: Role[], user: User): boolean {
```

2021-05-17 02:30 UTC, CaliCastle commented on src/guards/roles.guard.ts
> +  private checkUserExists(user?: User): boolean {
可能叫 `userMustExistOrFail` 这种会比直观

2021-05-17 02:30 UTC, CaliCastle commented on src/guards/roles.guard.ts
> +    if (!roles.some((role) => user!.role.includes(role))) {
user.role 不是一个string enum么 可以直接值===

2021-05-17 08:04 UTC, merged