变更用户数据结构&新增username的sluggable
zolran-studio/zhihuyou.server pull request #17
Opened 2021-05-20 11:25 UTC by Whx-Tim

删减firstname & lastname，新增full name；新增username；新增username的 @username路由匹配；调整原来firstname & lastname的相关名称与测试逻辑。

2021-05-20 12:37 UTC, CaliCastle requested changes
username改一下就差不多，👍

2021-05-20 12:37 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
> +    //TODO: another user's summary data, like post count, user's profile, like count, comment count etc.
考虑周到 👍🏼

2021-05-20 12:37 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
> +      user: modelFactory.make(UserClient, user),
这里的话可以直接返回user作为整个payload 不需要嵌套个user key了 本身就是个user

2021-05-20 12:37 UTC, CaliCastle commented on prisma/schema.prisma
> +  username    String?  @unique
username还是required的比较保险

2021-05-20 12:37 UTC, CaliCastle commented on test/users/users.e2e-spec.ts
> +        .expect(HttpStatus.UNAUTHORIZED)
好像如果auth guard的有点太保守了 应该可以public fetch

2021-05-20 15:29 UTC, Whx-Tim commented on src/controllers/users/users.controller.ts
> +      user: modelFactory.make(UserClient, user),
这个的话，是因为考虑到可能会存在其他不同于User的数据信息会一起返回，如果直接就是返回user的话，那数据结构就会大变，会在父级多一层嵌套，但是已经预计好了肯定会有其他比如user profile, like count, 等等这些统计数据的话，只要拓展对象的children就可以兼容整体的数据结构，算是考虑到后续最小改动才这么嵌套的。

2021-05-20 15:30 UTC, Whx-Tim commented on test/users/users.e2e-spec.ts
> +        .expect(HttpStatus.UNAUTHORIZED)
保守？举个例子，这个我没看懂~

2021-05-20 16:06 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
> +      user: modelFactory.make(UserClient, user),
因为前端涉及到entity的schema定义 所以也比较方便返回的直接是一个entity（model），可以比如说后面复杂了以后返回的是 `type UserPayload = User & UserProfile & Comments & Likes` 将多个interface/type进行union联合

2021-05-20 16:07 UTC, CaliCastle commented on test/users/users.e2e-spec.ts
> +        .expect(HttpStatus.UNAUTHORIZED)
就是说如果用户未登录就不给看的话有一点点强制

2021-05-20 16:08 UTC, CaliCastle commented on src/controllers/users/users.controller.ts
> +      user: modelFactory.make(UserClient, user),
或者利用 `@Expose()` 里面传参设置scope也是ok的

2021-05-20 16:09 UTC, Whx-Tim commented on test/users/users.e2e-spec.ts
> +        .expect(HttpStatus.UNAUTHORIZED)
哈哈哈哈哈哈，是的，未登录的话，确实不给看~ 礼尚往来，你要看我网站的用户信息，你起码要是我的用户呀~ 当然是可以做信息区分的，这个也可以~ 要不暂时先强制一点？

2021-05-20 16:11 UTC, Whx-Tim commented on src/controllers/users/users.controller.ts
> +      user: modelFactory.make(UserClient, user),
这样，那行~ 我一并改一下。

2021-05-20 16:13 UTC, CaliCastle commented on test/users/users.e2e-spec.ts
> +        .expect(HttpStatus.UNAUTHORIZED)
那也ok吧

2021-05-21 00:32 UTC, CaliCastle requested changes
小小问题稍改一下即可

2021-05-21 00:32 UTC, CaliCastle commented on src/services/users/admin.service.ts
> +                `username ${data.username} already exists.`
```suggestion
                `Username ${data.username} already exists.`
```

2021-05-21 00:32 UTC, CaliCastle commented on src/services/users/admin.service.ts
> +            throw new NotFoundException('The User to update is not found.')
```suggestion
            throw new NotFoundException('The user cannot be found.')
```

2021-05-21 00:32 UTC, CaliCastle commented on src/services/users/admin.service.ts
> +              `username ${data.username} already exists.`
```suggestion
              `Username ${data.username} already exists.`
```

2021-05-21 00:32 UTC, CaliCastle commented on src/services/users/auth.service.ts
> +                `username ${rest.username} already exists.`
这里的error check感觉可以提取一个helper function了

2021-05-21 00:32 UTC, CaliCastle commented on src/services/users/auth.service.ts
> +                `username ${rest.username} already exists.`
```suggestion
                `Username ${rest.username} already exists.`
```

2021-05-21 00:32 UTC, CaliCastle commented on test/users/users.e2e-spec.ts
> +          username: '我的名字',
👑    🌊    ⭐

2021-05-21 04:30 UTC, Whx-Tim commented on src/services/users/auth.service.ts
> +                `username ${rest.username} already exists.`
哈哈哈哈哈，是的。我昨晚试过了，但是好像发现用途没有特别多，然后就没有提取了。

2021-05-21 07:01 UTC, CaliCastle approved these changes

2021-05-21 07:01 UTC, merged